### ISSUE TITLE
The format of the datasets

### ISSUE THREAD

**Issue by Z2HENG** [AlbertoSabater/Skeleton-based-One-shot-Action-Recognition#1]
The data format we used may be different. What is the format of each NPY file in NTU RGB+D 120 dataset. Could you please give an example of the skeleon.npy file ? Thanks!

**Comment by AlbertoSabater** [comment]
Hi! Different to what? The joints format is the same that the Kinect Cameras have as default. I no longer have this dataset but you can download it from their author's [web page](https://rose1.ntu.edu.sg/dataset/actionRecognition/).

**Comment by Z2HENG** [comment]
> Hi! Different to what? The joints format is the same that the Kinect Cameras have as default. I no longer have this dataset but you can download it from their author's [web page](https://rose1.ntu.edu.sg/dataset/actionRecognition/).
Thanks for your reply!

**Comment by Lululu100** [comment]
> The data format we used may be different. What is the format of each NPY file in NTU RGB+D 120 dataset. Could you please give an example of the skeleon.npy file ? Thanks!

Hello, your work is excellent! I downloaded from https://rose1.ntu.edu.sg/dataset/actionRecognition/ web site dataset skeleton format file, for example "S002C001P013R002A051. Skeleton, and in accordance with the requirements in the". / datasets/NTU - 120 / raw_npy/" file, But the code "ntu_annotations" need in file format for the ". / datasets/NTU - 120 / raw_npy S002C001P013R002A051 skeleton. The npy ", could you tell me how should I do? Can you describe in detail the process of data processing? Thank you very much and look forward to your reply.
